title:              Ayushman Devraj
email:              aydevraj@gmail.com
description:        Homepage
author:             Ayushman Devraj
baseurl:            "/"
url:                "https://ayushmandevraj.in"

# Social Profiles
twitter_username:   aydevraj
facebook_username: aydevraj
instagram_username: aydevraj

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-144724692-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag